services:
  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: postulations
    volumes:
      - data-mysql:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - spring
  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: mysql8:3306
      DB_DATABASE: postulations
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - spring
    restart: always
    depends_on:
      - mysql-container
  frontend:
    build:
      dockerfile: frontend/frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - spring
    depends_on:
      - backend
volumes:
  data-mysql:
    name: data-mysql
networks:
  spring: